# Customer Analytics Project 
## Exploración Inicial de Datos
El objetivo de este notebook es realizar una exploración inicial del dataset para comprender su estructura y evaluar la calidad de los datos.
### Calidad de los datos
Se analizarán:
- Hojas disponibles en el archivo
- Cantidad de registros y campos
- Significado de las variables
- Tipos de datos
- Valores presentes en los principales campos
- Valores nulos y duplicados
- Posibles inconsistencias que requieran limpieza

In [33]:
import pandas as pd

In [34]:
# ExcelFile nos permite inspeccionar el archivo Excel
excel = pd.ExcelFile(r'C:\Users\solan\customer-intelligence-analytics\data\raw\online_retail_II.xlsx')

In [35]:
# Hojas disponibles en el archivo
excel.sheet_names

['Year 2009-2010', 'Year 2010-2011']

In [36]:
#Poner el excel en un dataframe para poder trabajar con él
df = pd.read_excel(r'C:\Users\solan\customer-intelligence-analytics\data\raw\online_retail_II.xlsx')

KeyboardInterrupt:

In [ ]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

| Campo         | Interpretación inicial               |
| ------------- | ------------------------------------ |
| `Invoice`     | Identificador de factura/transacción |
| `StockCode`   | Identificador del producto           |
| `Description` | Descripción del producto             |
| `Quantity`    | Cantidad de unidades                 |
| `InvoiceDate` | Fecha/hora de la factura             |
| `Price`       | Precio unitario                      |
| `Customer ID` | Identificador del cliente            |
| `Country`     | País                                 |

In [ ]:
df_2010_2011 = pd.read_excel(
    r'C:\Users\solan\customer-intelligence-analytics\data\raw\online_retail_II.xlsx',
    sheet_name='Year 2010-2011'
)

df_2009_2010 = pd.read_excel(
    r'C:\Users\solan\customer-intelligence-analytics\data\raw\online_retail_II.xlsx',
    sheet_name='Year 2009-2010'
)

In [ ]:
df_2010_2011.shape

(541910, 8)

In [ ]:
df_2009_2010.shape

(525461, 8)

In [ ]:
df_2009_2010.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [ ]:
df_2010_2011.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [ ]:
pd.concat?

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool | lib.NoDefault' = <no_default>,
    copy: 'bool | lib.NoDefault' = <no_default>,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : an iterable or mapping of Series or DataFrame objects
    If a mapping is passed, the keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, default 0
    The axis to concatenate along.
join : {'inner', 'outer'}, default 'outer'
    How to handle indexes on other axis (or axes).
ignore_index : bool, default False
    If True, do not use the index values along the concatenation axis. The
    resulting axis will be labeled 0, ..., n - 1. This is useful if you are
    concatenating objects where the concatenation axis does not have
    meaningful indexing information. Note the index values on the other
    axes are still respected in the join.
keys : sequence, default None
    If multiple levels passed, should contain tuples. Construct
    hierarchical index using the passed keys as the outermost level.
levels : list of sequences, default None
    Specific levels (unique values) to use for constructing a
    MultiIndex. Otherwise they will be inferred from the keys.
names : list, default None
    Names for the levels in the resulting hierarchical index.
verify_integrity : bool, default False
    Check whether the new concatenated axis contains duplicates. This can
    be very expensive relative to the actual data concatenation.
sort : bool, default False
    Sort non-concatenation axis. One exception to this is when the
    non-concatenation axis is a DatetimeIndex and join='outer' and the axis is
    not already aligned. In that case, the non-concatenation axis is always
    sorted lexicographically.
copy : bool, default False
    This keyword is now ignored; changing its value will have no
    impact on the method.

    .. deprecated:: 3.0.0

        This keyword is ignored and will be removed in pandas 4.0. Since
        pandas 3.0, this method always returns a new object using a lazy
        copy mechanism that defers copies until necessary
        (Copy-on-Write). See the `user guide on Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        for more details.

Returns
-------
object, type of objs
    When concatenating all ``Series`` along the index (axis=0), a
    ``Series`` is returned. When ``objs`` contains at least one
    ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
    the columns (axis=1), a ``DataFrame`` is returned.

See Also
--------
DataFrame.join : Join DataFrames using indexes.
DataFrame.merge : Merge DataFrames by indexes or columns.

Notes
-----
The keys, levels, and names arguments are all optional.

A walkthrough of how this method fits in with other tools for combining
pandas objects can be found `here
<https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

It is not recommended to build DataFrames by adding single rows in a
for loop. Build a list of rows and make a DataFrame in a single concat.

Examples
--------
Combine two ``Series``.

>>> s1 = pd.Series(["a", "b"])
>>> s2 = pd.Series(["c", "d"])
>>> pd.concat([s1, s2])
0    a
1    b
0    c
1    d
dtype: str

Clear the existing index and reset it in the result
by setting the ``ignore_index`` option to ``True``.

>>> pd.concat([s1, s2], ignore_index=True)
0    a
1    b
2    c
3    d
dtype: str

Add a hierarchical index at the outermost level of
the data with the ``keys`` option.

>>> pd.concat([s1, s2], keys=["s1", "s2"])
s1  0    a
    1    b
s2  0    c
    1    d
dtype: str

Label the index keys you create with the ``names`` option.

>>> pd.concat([s1, s2], keys=["s1", "s2"], names=["Series name", "Row ID"])
Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: str

Combine two ``DataFrame`` objects with identical columns.

>>> df1 = pd.DataFrame([["a", 1], ["b", 2]], columns=["letter", "number"])
>>> df1
  letter  number
0      a       1
1      b       2
>>> df2 = pd.DataFrame([["c", 3], ["d", 4]], columns=["letter", "number"])
>>> df2
  letter  number
0      c       3
1      d       4
>>> pd.concat([df1, df2])
  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Combine ``DataFrame`` objects with overlapping columns
and return everything. Columns outside the intersection will
be filled with ``NaN`` values.

>>> df3 = pd.DataFrame(
...     [["c", 3, "cat"], ["d", 4, "dog"]], columns=["letter", "number", "animal"]
... )
>>> df3
  letter  number animal
0      c       3    cat
1      d       4    dog
>>> pd.concat([df1, df3], sort=False)
  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

Combine ``DataFrame`` objects with overlapping columns
and return only those that are shared by passing ``inner`` to
the ``join`` keyword argument.

>>> pd.concat([df1, df3], join="inner")
  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Combine ``DataFrame`` objects horizontally along the x axis by
passing in ``axis=1``.

>>> df4 = pd.DataFrame(
...     [["bird", "polly"], ["monkey", "george"]], columns=["animal", "name"]
... )
>>> pd.concat([df1, df4], axis=1)
  letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

Prevent the result from including duplicate index values with the
``verify_integrity`` option.

>>> df5 = pd.DataFrame([1], index=["a"])
>>> df5
   0
a  1
>>> df6 = pd.DataFrame([2], index=["a"])
>>> df6
   0
a  2
>>> pd.concat([df5, df6], verify_integrity=True)
Traceback (most recent call last):
    ...
ValueError: Indexes have overlapping values: ['a']

Append a single row to the end of a ``DataFrame`` object.

>>> df7 = pd.DataFrame({"a": 1, "b": 2}, index=[0])
>>> df7
    a   b
0   1   2
>>> new_row = pd.Series({"a": 3, "b": 4})
>>> new_row
a    3
b    4
dtype: int64
>>> pd.concat([df7, new_row.to_frame().T], ignore_index=True)
    a   b
0   1   2
1   3   4
File:      ~\customer-intelligence-analytics\.venv\lib\site-packages\pandas\core\reshape\concat.py
Type:      function

In [ ]:
# En Pandas, el equivalente más directo a un UNION ALL de SQL es pd.concat()
# Pandas concat = pegar estructuras: axis=0 hacia abajo; axis=1 hacia el costado.
# ignore_index=True hace que Pandas genere nuevamente el índice de filas 0, 1, 2, 3... para el DataFrame unificado

df_all = pd.concat(
    [df_2009_2010, df_2010_2011],
    ignore_index=True
)

In [ ]:
# df_all será nuestro dataset de trabajo completo
df_all.shape

(1067371, 8)

In [ ]:
# data types de las columnas en df_all
df_all.dtypes

# Concepto: "object"--> Pandas no puede tratar Invoice simplemente como un número porque puede contener valores alfanuméricos

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

Tipos que se pueden a encontrar habitualmente:

|Pandas	        |Significado aproximado                |
| ------------- | ------------------------------------ |
|object	        |Texto, valores mixtos u objetos Python|
|string	        |Texto                                 |
|int64	        |Número entero                         |
|float64	    |Número decimal                        |
|bool	        |Verdadero/falso                       |
|datetime64[...]	|Fecha/hora                        |

```text
df_all
↓
          ['Column_name']    → si se quiere explorar solo una  ( sino no se pone nada )
↓
.isna()            → marcá True donde haya NULL/NaN
↓
.sum()             → sumá los True
↓
243.007 nulos
```

In [ ]:
df_all.isna().sum()  # df_all['Customer ID'].isna().sum()  → si se quiere explorar solo una

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [ ]:
# voy a ver un par de filas para ver cómo se ven los casos con valores nulos en Customer ID o Description
df_all[df_all['Description'].isna()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1060783,581199,84581,NaN,-2,2011-12-07 18:26:00,0.0,NaN,United Kingdom
1060787,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,NaN,United Kingdom
1060793,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,NaN,United Kingdom
1062442,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
1064015,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom

```text
Se lee como : 
del data frame df_all 
              ↓
[ df_all['Description'].isna() ]
              ↓
      condición/filtro
              ↓
"devolveme las filas donde Description es NULL"

In [ ]:
# Busco comprobar si todas las filas donde  Description = NULL también tienen Customer ID = NULL

df_all[(df_all['Description'].isna()) & (df_all['Customer ID'].isna())].shape[0]

# y queda comprobado

4382

 Basicamente en todos los casos donde la descripcion es Nula el Id_customer tambien lo es

 Ahora quiero ver los otros casos donde la descripcion no es nula y el id_customer si lo es.

 También me interesaría ver si tiene algun factor en común, ej: si los nulos se distribuyen en todos los paises en gral o si está concentrado en 1 pais puntual.

In [ ]:
df_all[(df_all['Description'].notna()) & (df_all['Customer ID'].isna())]

In [ ]:
# Guardo el filtro en un DataFrame para no repetirlo constantemente

df_sin_customer = df_all[
    (df_all['Customer ID'].isna()) &
    (df_all['Description'].notna())
]

In [ ]:
# Conteo de registros por país en el DataFrame sin Customer ID
df_sin_customer['Country'].value_counts()

# nos permite descubrir si los clientes sin identificar están concentrados en determinados países o si aparecen de manera general

# el 98,75%

Country
United Kingdom          235647
EIRE                      1671
Hong Kong                  364
Unspecified                232
France                     128
Switzerland                125
Portugal                   116
United Arab Emirates       114
Bahrain                     67
Israel                      47
RSA                         46
Bermuda                     34
Sweden                      19
Lebanon                     13
Nigeria                      2
Name: count, dtype: int64

In [ ]:
# Estadísticas descriptivas de las columnas Quantity y Price en el DataFrame sin Customer ID
df_sin_customer[['Quantity', 'Price']].describe()

            Quantity          Price
count  238625.000000  238625.000000
mean        1.885833       8.094711
std        71.946304     226.322727
min     -9600.000000  -53594.360000
25%         1.000000       1.660000
50%         1.000000       3.360000
75%         2.000000       5.790000
max     10200.000000   25111.090000

In [ ]:
df_sin_customer[
    df_sin_customer['Price'] < 0
]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom

In [ ]:
# ¿Cuántas facturas Adjust bad debt hay sin Customer ID?

df_sin_customer[df_sin_customer['Description'] == 'Adjust bad debt']['Invoice'].nunique() 
# Cuenta las facturas únicas con Description = 'Adjust bad debt'
# dentro del universo sin Customer ID hay solo 6 facturas

6

In [ ]:
# ¿Hay casos Adjust bad debt con Customer ID?  = NO 
df_all[(df_all['Description'] == 'Adjust bad debt') & (df_all['Customer ID'].notna())]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [ ]:
# Listo los 20 productos sin customer id más frecuentes 
df_sin_customer['Description'].value_counts().head(20)

# Los registros sin Customer ID contienen mayoritariamente descripciones que parecen productos normales

Description
DOTCOM POSTAGE                        1428
JUMBO BAG RED RETROSPOT                693
JUMBO STORAGE BAG SUKI                 635
REGENCY CAKESTAND 3 TIER               635
PARTY BUNTING                          621
WHITE HANGING HEART T-LIGHT HOLDER     603
RECYCLING BAG RETROSPOT                573
JUMBO SHOPPER VINTAGE RED PAISLEY      529
WOODLAND CHARLOTTE BAG                 526
JUMBO BAG WOODLAND ANIMALS             509
STRAWBERRY CERAMIC TRINKET BOX         507
RED TOADSTOOL LED NIGHT LIGHT          505
SUKI  SHOULDER BAG                     488
CHARLOTTE BAG SUKI DESIGN              465
JUMBO  BAG BAROQUE BLACK WHITE         444
SMALL HEART MEASURING SPOONS           435
PACK OF 60 PINK PAISLEY CAKE CASES     434
LOVEBIRD HANGING DECORATION WHITE      432
GREEN REGENCY TEACUP AND SAUCER        427
NATURAL SLATE HEART CHALKBOARD         426
Name: count, dtype: int64

In [ ]:
# trato de buscar la Factura que tiene la descripcion Adjust bad debt en el dataframe general para saber si ese ajuste es sobre la misma factura que tiene el precio negativo

df_all[df_all['Invoice'] == 'A506401']

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom

In [ ]:
df_all.duplicated().sum()

# Me está diciendo:

# Encontré 34.335 filas que son exactamente iguales a una fila anterior considerando todas las columnas

np.int64(34335)

In [ ]:
# vemos un par de casos duplicados para ver si son realmente iguales o si hay alguna diferencia en alguna columna
df_all[df_all.duplicated()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom

In [41]:
# Marcame todas las filas que tengan otra idéntica, incluida la primera.
df_duplicados = df_all[
    df_all.duplicated(keep=False)
]

# Podemos ordenar por Invoice y StockCode
df_duplicados = df_duplicados.sort_values(
    by=['Invoice', 'StockCode']
)

# vemos el output de los 20 primeros registros duplicados
df_duplicados.head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom

Se detectaron **34.335 filas duplicadas**, pero no se eliminan porque no existe un identificador de línea (`Line Item`) que permita saber si son duplicados reales o varias unidades del mismo producto registradas en líneas separadas. Eliminarlas podría provocar una pérdida de ventas válidas y subestimar cantidades e importes.